### ISSUE TITLE
哈希签名并不能保证候选点和查询点的label相同

### ISSUE THREAD

**Issue by ryanpipi233** [pkumod/GSI#3]
代码来自Graph.cpp 62行
`int pos = myhash(&(v.label), 4, HASHSEED) % VLEN;
        signature_table[signum*i] = 1 << pos;`

**Comment by bookug** [comment]
实际上这里使用的是一种特殊的处理方式，label 32位整数被直接复制到signature的起始。对比这部分时采用的是==判断，而不是检查包含关系

**Comment by ryanpipi233** [comment]
> 实际上这里使用的是一种特殊的处理方式，label 32位整数被直接复制到signature的起始。对比这部分时采用的是==判断，而不是检查包含关系

我没有找到"label 32位整数被直接复制到signature的起始"的代码实现，能指出一下不；对于验证，论文的实现是 usig&vsig == usig，这一点我能够理解

**Comment by ryanpipi233** [comment]
我没有找到"label 32位整数被直接复制到signature的起始"的代码实现，能指出一下不；对于验证，论文的实现是 usig&vsig == usig，这一点我能够理解

**Comment by bookug** [comment]
这个代码比较久了。。我不确定上传的这份代码是否包含了整数==这部分。如果没有，可以简单修改下，也很快

**Comment by ryanpipi233** [comment]
已收到材料，谢谢！

**Comment by ryanpipi233** [comment]
已收到材料，谢谢！
